[target.riscv32imac-unknown-none-elf]
runner = "espflash"

[build]
target = "riscv32imac-unknown-none-elf"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "link-arg=-Tdefmt.x",
]

[unstable]
build-std = ["core"]

[env]
DEFMT_LOG = "debug"